# Generated by Django 3.2.25 on 2024-09-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('releaseYear', models.CharField(max_length=500)),
                ('director', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('duration', models.CharField(max_length=50)),
                ('genre', models.JSONField()),
                ('language', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('starring', models.JSONField()),
            ],
        ),
    ]
